# spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=update

# # show sql method 1
# # spring.jpa.show-sql=true
# # format sql
# spring.jpa.properties.hibernate.format_sql=true


# # show sql method 2 with logging query parameters
# logging.level.org.hibernate.SQL=DEBUG
# # logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.level.org.hibernate.orm.jdbc.bind=TRACE



# # App Properties
# bezkoder.app.jwtSecret=======================Harry===========================
# # 1 day
# bezkoder.app.jwtExpirationMs=86400000

# # springdoc.api-docs.enabled=true
# # springdoc.swagger-ui.enabled=true
# # springdoc.api-docs.path=/v3/api-docs
# # springdoc.swagger-ui.path=/swagger-ui.html

# Above is application.properties file, converting it into application.yml file

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/jwtdb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  PostgreSQL example
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  # Default username and password for the database
  security:
    user:
      name: yousuf
      password: yousuf
  
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
  # Logging level order: TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
  
yousuf:
  app:
    # jwtSecret: -****************************************MYousuf****************************************-
    jwtSecret: =========================================MYousuf=========================================
    jwtExpirationTimeInMs: 86400000         # 1 day = 24 hrs = 86400 sec = 86400000 ms
    # jwtExpirationTimeInMs: 120000           # 2 min = 120 sec = 120000 ms

# Set context path /api
server:
  servlet:
    context-path: /api


# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true
#   api-docs:

# Enable Swagger/OpenAPI documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
