spring:
  datasource:
    #    MySQL
    #    url: jdbc:mysql://localhost:3306/jwtdb
    #    username: root
    #    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #  PostgresSQL
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  # Default username and password for the database
  security:
    user:
      name: yousuf
      password: yousuf

  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
  # Logging level order: TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF

yousuf:
  app:
    # jwtSecret: -****************************************MYousuf****************************************-
    jwtSecret: =========================================MYousuf=========================================
    jwtExpirationTimeInMs: 86400000         # 1 day = 24 hrs = 86400 sec = 86400000 ms
    # jwtExpirationTimeInMs: 120000           # 2 min = 120 sec = 120000 ms

# Set context path /api
server:
  servlet:
    context-path: /api


# Enable Swagger/OpenAPI documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
